name: Daily Commit

on:
  schedule:
    - cron: '35 4 * * *'
  workflow_dispatch:

jobs:
  daily-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make dummy commit by 23f3003961@ds.study.iitm.ac.in
        run: |
          echo "Daily update on $(date)" >> daily-log.txt
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Show current git status
          git status

          git add daily-log.txt

          # Check if there's anything to commit
          if git diff --cached --quiet; then
            echo "Nothing to commit."
          else
            git commit -m "Automated daily commit"
            git push origin HEAD
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


